version: "3.7"
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wisely_test
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - DATABASE_CONNECTION_STRING=postgres://postgres:password@db/wisely_test
      - NODE_ENV=development
      - APP_ENV=development
      - PORT=8080
      - LOG=debug
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "9090:8080"
    volumes:
      # Mount the folder for dev work
      - ./api:/app
      # Exclude the node modules folder so that local env doesn't mix with image
      - /app/node_modules/
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    volumes:
      # Mount the folder for dev work
      - ./frontend:/app
      # Exclude the node modules folder so that local env doesn't mix with image
      - /app/node_modules/
    ports:
      - "8080:8080"
      - "8081:8081"
